#version: '3.8'

services:
  mongo:
    build: mongodb/.
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_DATABASE: admin
      MONGO_USERNAME_FILE: /run/secrets/mongodb_username
      MONGO_PASSWORD_FILE: /run/secrets/mongodb_password
      MONGO_DATABASE: iswars
    secrets:
      - mongodb_root_password
      - mongodb_root_username
      - mongodb_password
      - mongodb_username
    networks:
      - islands
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/iswars --quiet
      interval: 2s
      timeout: 12s
      retries: 5
      start_period: 10s
    volumes:
      - ./mongodb/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    command: [--auth]

  commons:
    build: .
    networks:
      - islands
    secrets:
      - redis_password
      - mongodb_password
      - mongodb_username
      - mongodb_host
      - mongodb_port
    depends_on:
      mongo:
        condition: service_healthy

networks:
  islands:
    driver: bridge

secrets:
  redis_password:
    file: secrets/redis_password
  mongodb_root_password:
    file: secrets/mongodb_root_password
  mongodb_root_username:
    file: secrets/mongodb_root_username
  mongodb_password:
    file: secrets/mongodb_password
  mongodb_username:
    file: secrets/mongodb_username
  mongodb_host:
    file: secrets/mongodb_host
  mongodb_port:
    file: secrets/mongodb_port
