name: Commons plugin

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name : Setup Java 20
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '20'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew jar
      - name: Publish to GitHub Packages
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: ./gradlew publish
        env:
          USERNAME: ${{ secrets.GPR_ACTOR }}
          TOKEN: ${{ secrets.GPR_TOKEN }}